#!/usr/bin/env python3
# Renders the user interface font into font.h (anti-aliased glyphs, one
# byte of coverage per pixel). Needs python3-pil.
#   python3 tools/mkfont.py [font.ttf [pixel size]] > font.h
# The default is Noto Sans (SIL Open Font License 1.1), 12 px = 9 pt at 96 dpi.
import sys
from PIL import ImageFont

path = sys.argv[1] if len(sys.argv) > 1 else \
    "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"
size = int(sys.argv[2]) if len(sys.argv) > 2 else 12

ranges = [(0x20, 0x7e), (0xa0, 0xff), (0x400, 0x45f), (0x2010, 0x2027),
          (0x2030, 0x203a), (0x20ac, 0x20ac), (0x2116, 0x2116),
          (0x2122, 0x2122), (0x2190, 0x2193), (0x2212, 0x2212)]

font = ImageFont.truetype(path, size)
ascent, descent = font.getmetrics()
glyphs = []
data = bytearray()
for lo, hi in ranges:
    for cp in range(lo, hi + 1):
        ch = chr(cp)
        # skip code points the font has no glyph for
        if cp > 0x20 and font.getmask(ch).getbbox() is None and cp != 0xa0:
            continue
        adv = int(round(font.getlength(ch)))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(data)
        if w and h:
            mask, (mx, my) = font.getmask2(ch, mode="L", anchor="ls")
            x0, y0 = mx, my
            w, h = mask.size
            for y in range(h):
                for x in range(w):
                    data.append(mask.getpixel((x, y)))
        glyphs.append((cp, x0, y0, w, h, adv, off))

name = font.getname()
out = sys.stdout
out.write("/* generated by tools/mkfont.py from %s %s, %d px\n" % (name[0], name[1], size))
out.write(" *\n"
          " * Glyph images of Noto Sans, Copyright 2012 Google Inc.,\n"
          " * licensed under the SIL Open Font License, Version 1.1\n"
          " * (https://openfontlicense.org), see LICENSE. */\n\n")
out.write("static const int fontascent = %d;\n" % ascent)
out.write("static const int fontdescent = %d;\n\n" % descent)
out.write("/* code point, offset from the pen position to the top left corner\n"
          " * (y is negative above the baseline), size, advance, data offset */\n")
out.write("static const struct glyph {\n\tunsigned short cp;\n\tsigned char x, y;\n"
          "\tunsigned char w, h, adv;\n\tunsigned int off;\n} glyphs[] = {\n")
for g in glyphs:
    out.write("\t{ 0x%04x, %d, %d, %d, %d, %d, %d },\n" % g)
out.write("};\n\n")
out.write("static const unsigned char glyphdata[] = {\n")
for i in range(0, len(data), 16):
    out.write("\t" + ", ".join("%d" % b for b in data[i:i + 16]) + ",\n")
out.write("};\n")
